# datasource PostgreSQL
spring:
  application:
    name: produto
  datasource:
    url: jdbc:postgresql://localhost:5432/produtosdb
    username: postgres
    password: post@2806

#JPA
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

